### ISSUE TITLE
Provide arm64 Darwin build

### ISSUE THREAD

**Issue by kumy** [dimo414/bkt#17]
Hi @dimo414 

could you please provide release builds for `arm64 Darwin`?

Thanks :pray:

**Comment by dimo414** [comment]
Sure, do you want to add it [here](https://github.com/dimo414/bkt/blob/aed4c817b93c08baccc09dd5f50f9956c7a27c19/.github/workflows/rust.yml#L39)?

**Comment by dimo414** [comment]
It seems cross doesn't support arm64 Darwin builds yet. For the time being I'm going to recommend installing from source, either using Homebrew (`brew install bkt`) or Cargo (`cargo install bkt`). Someone could take a swing at manually setting up a build without cross, but given that there are easy alternatives I'm not planning to prioritize doing so myself.

**Comment by kumy** [comment]
Thanks for taking time to look at it. `brew install` is a good alternative. 👍

**Comment by dimo414** [comment]
@kumy if you want to take another swing at it, it might be possible now judging from https://github.com/sharkdp/fd/pull/1552 - I'll get to it soon if you don't.

**Comment by kumy** [comment]
Thanks @dimo414 
I created PR https://github.com/dimo414/bkt/pull/52. Hope this help
