### ISSUE TITLE
[Feature suggestion] Flag to report bkt invocation values, and bkt context

### ISSUE THREAD

**Issue by mcint** [dimo414/bkt#22]
I'd like a flag analogous to report Bkt status values. A one line output

As a baseline, a report of this invocation
`Bkt: in_cache: false, ttl: 600s, stale?, warm?, force?`

Perhaps repeated use of the flag, or a different flag, can report environment state consistent across invocations
`Bkt context: cache_dir: ..., scope, env(Hash): 5a5a5a, command: "[expensive-command]", cwd?`

Suggested names: [i]nclude (as in curl) / [v]erbose / [d]ebug  / [r]eport? / [s]tatus.

**Comment by dimo414** [comment]
Would #19 cover what you need? Can you share more about how you'd hope to use this information?

Note also the [`debug` feature](https://github.com/dimo414/bkt/blob/906056a3207c1ad79643490d85f0933cf4ade8ff/Cargo.toml#L23) which requires recompiling `bkt` but can be useful for debugging.

**Comment by dimo414** [comment]
I'm going to merge this with #19, feel free to weigh in there, it's something I'm likely to work on in the coming weeks.
