### ISSUE TITLE
Feature request: stream the subprocess' stdout and stderr while it's running

### ISSUE THREAD

**Issue by borestad** [dimo414/bkt#31]
Hi!

Really useful cli tool. I use this mostly for downloading large files in a cronjob.
Something that I'm currently lacking is a strategy for streaming the progress to stdout. Both in interactive and in CI-scripts.

What are your thoughts about this?

**Comment by dimo414** [comment]
Thanks for filing, yes I'd like to implement this (for both stdout and stderr), similar to what [`fzf` did](https://github.com/junegunn/fzf/pull/2215). This is mentioned in the README and [a few other places](https://github.com/dimo414/bkt/blob/e52bd6f92f/src/lib.rs#L1061-L1062) but there should be a tracking issue.

I _think_ this is fairly straightforward to implement, but it involves [spawning new threads to process stdout/stderr manaully](https://stackoverflow.com/q/66060139/113632) and I've just avoided pulling it together :) I'll try to take a swing at it in the next few weeks, but if you or anyone else is interested in sending a PR it shouldn't be _too_ much work.

**Comment by borestad** [comment]
Ah, I see. Unfortunately, Rust isn't my main language (although I can read the code). Otherwise you'd have a PR in notime.

As I see it, this together with a couple of more extra api's like "has" (to check if the value already exists) + "stats" with information about remaining ttl etc ...+ the ability to create a unique key instad of hashing the input ....would make me throw out almost all my current caching needs entirely! 🥰

**Comment by dimo414** [comment]
You might be interested in #24 and #19 as well in that case.

Would you mind starting a [discussion thread](https://github.com/dimo414/bkt/discussions) with more details about how you might use `bkt` if the additional features you're envisioning existed? It would be very helpful to understand your desired use-cases better.

**Comment by borestad** [comment]
Hi, sorry for late response. Fever got in the way.
Anyway, I wrote here to show my "memo" helper for streaming output.

I'll come back with other details of how I'm using bkt - but in the memo helper it's obvious that I need to use some "hacks" to acchieve:

- Check for an existing key
- Delete an existing key
- Show TTL left
- Create a unique key (to be able to delete it later)

**Comment by dimo414** [comment]
Thanks the the thoughts! I moved them to a [separate thread](https://github.com/dimo414/bkt/discussions/33) so it's easier to discuss further. For invalidation specifically you can also weigh in on #5.

**Comment by dimo414** [comment]
For folks interested in this issue, PR #43 will implement streaming support. Please take a look at the PR if you have any feedback before it's merged. You can also grab binaries off the [CI runs](https://github.com/dimo414/bkt/actions/runs/5864960970) to test these changes out locally.

**Comment by dimo414** [comment]
@borestad if you have a minute to try out PR #43 I'd appreciate it! Planning to merge and cut a new release in the next few days.

**Comment by borestad** [comment]
@dimo414 I did a quick test with just a minor script like:

```
sleep 1
echo 1
sleep 1
echo 2
sleep 1
echo 3
```
....works perfect! This is great stuff 👍
