### ISSUE TITLE
bkt: stdout pipe failed: failed to write whole buffer

### ISSUE THREAD

**Issue by agostonbarna** [dimo414/bkt#44]
Hi,
I recently ran into an error with bkt:
```sh
bkt -- find . -type f | head -n1
```
```
./file
bkt: Subprocess execution failed: stdout pipe failed: failed to write whole buffer
```

This only seem to happen with many files/lines, but I don't get the error when piping the stdout to `wc -l`, so maybe the issue only happens when the process on the right side of the pipe closes the stdout of the bkt process before it could write out it's whole output (e.g. `head`, `fzf`).
```sh
bkt -- find . -type f | wc -l
```
```
286910
```

The stdout is actually correct in both cases so it sounds like this bkt error is not really necessary to show to the user.

Reproduced with:
* bkt version: 0.7.0 (with `cargo install bkt`)
* macOS 13.5 (arm64)
* a fairly up to date arch linux (aarch64).

**Comment by dimo414** [comment]
Thanks for the report! 0.7.0 was just released so this is likely a regression (i.e. you can workaround via 0.6.1 in the meantime), I'll see if I can reproduce and fix.

**Comment by dimo414** [comment]
@agostonbarna would you mind trying out [these binaries](https://github.com/dimo414/bkt/actions/runs/5993392416) and confirming the issue is resolved on your end? I'll cut a 0.7.1 as soon as I hear from you.

**Comment by agostonbarna** [comment]
Hey @dimo414 ,
Wow, thanks for the quick fix! I checked again with both the previous (0.7.0) and your new bkt version (0.7.1), and I can only reproduce it with the old one, so it looks good 👍

**Comment by dimo414** [comment]
Thanks for confirming!
