### ISSUE TITLE
bkt should make scope "filename-safe"

### ISSUE THREAD

**Issue by larsks** [dimo414/bkt#50]
My very first use of `bkt` was to cache the output of a `kubectl` command. I want the results scoped to a particular cluster, so I did this:

```
export BKT_SCOPE=$(kubectl config view --minify -o json | jq .clusters[0].cluster.server)
```

This ends up with `BKT_SCOPE` having a value like `https://api.cluster.example.com:6443`, which ultimately causes `bkt` to fail with:

```
bkt: Cache write failed: No such file or directory (os error 2)
```

And this is because it's trying to use the scope literally as part of a pathname:

```
1142219 rename("/tmp/bkt-0.7-cache/keys/tmp-symlink.TysE1Bh1WR7I7TDH", "/tmp/bkt-0.7-cache/keys/\"https://api.cluster.example.com:6443\".4EBF7E540DA5C7C7") = -1 ENOENT (No such file or directory)
```

Either...

(a) The documentation should make it clear that scope value is used verbatim in a pathname and must not contain any "path sensitive" characters (and `bkt` should probably throw an error if it detects things like `/` or `\` in the scope value), or

(b) `bkt` should sanitize the path (e.g., to only ascii alphanumerics or something), so that the above might result in the path `.../keys/https___api_cluster_example_com_6443...`.

(c) or maybe just base64-encode the scope value.

**Comment by dimo414** [comment]
Thanks for the feedback and suggestions! I agree it's surprising scopes don't work with those inputs, I think base64-ing is a reasonable fix. Would you be interested in contributing that change? Otherwise I'll take a swing at it some time in the next few weeks.

**Comment by larsks** [comment]
I'll take a look at it. I have zero Rust experience, so it might take me a bit. If I haven't put something together within the next week, it's probably not going to happen.
