### ISSUE TITLE
bkt version incorrect in Cargo.lock

### ISSUE THREAD

**Issue by tranzystorekk** [dimo414/bkt#55]
In 0.8.1, updating the version in the `Cargo.lock` file must have slipped through the cracks, now building with `--locked` fails.

**Comment by dimo414** [comment]
Ugh, I've forgotten that before too 🙄 Fixed, and added `--locked` to the CI/CD steps.

Is it a bad idea to just bump the 0.8.1 tag to b7b07299, or should I cut a 0.8.2 to address it?

**Comment by tranzystorekk** [comment]
The package maintainer in me prefers cutting 0.8.2 to keep the tags clean
