### ISSUE TITLE
Relative cache path does not cache as expected

### ISSUE THREAD

**Issue by rrx** [dimo414/bkt#9]
The following does not seem to cache:
```
rm -rf asdf
# takes 10 seconds as expected
time cargo run -- --cache-dir asdf -- sleep 10
# also takes 10 seconds
time cargo run -- --cache-dir asdf -- sleep 10
```
The second invocation should return immediately but does not.

But if I specify the absolute path, it works as expected:
```
rm -rf asdf
# takes 10 seconds
time cargo run -- --cache-dir $PWD/asdf -- sleep 10
# returns immediately
time cargo run -- --cache-dir $PWD/asdf -- sleep 10
```

I haven't discovered why this is happening in the code, but the quick solution I came up with was to canonicalize the cache path.  At some point the path is getting expanded out.  Not sure where.

The following fixes the issue: https://github.com/dimo414/bkt/pull/8

**Comment by dimo414** [comment]
Interesting finding! Quick tip: you can compile with `--features debug` to have `bkt` output diagnostic information like the paths its interacting with.

The issue appears to be the key->data file symlink, which is being created as a relative symlink relative to the cwd despite being in a subdirectory:

```shell
$ cargo run --features debug -- --cache-dir asdf -- sleep 2
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target/debug/bkt --cache-dir asdf -- sleep 2`
bkt: lookup asdf/bkt-0.5-cache/keys/sleep-2_9E1A0833A39872EA not found
bkt: cleanup data asdf/bkt-0.5-cache/data
bkt: cleanup keys asdf/bkt-0.5-cache/keys
bkt: store data asdf/bkt-0.5-cache/data/60/data.qs79ZXF6nUTYJynQ
bkt: store key asdf/bkt-0.5-cache/keys/sleep-2_9E1A0833A39872EA

$ readlink asdf/bkt-0.5-cache/keys/sleep-2_9E1A0833A39872EA
asdf/bkt-0.5-cache/data/60/data.qs79ZXF6nUTYJynQ

$ readlink -m asdf/bkt-0.5-cache/keys/sleep-2_9E1A0833A39872EA
/Users/dimo414/Workspace/bkt/asdf/bkt-0.5-cache/keys/asdf/bkt-0.5-cache/data/60/data.qs79ZXF6nUTYJynQ
```

So, we _can_ just canonicalize the path the user provides, but fixing the symlink should also work. I'm gonna take a swing at that just to see, LMK if you think your approach is preferable.
